### ISSUE TITLE
Incompatible with go-ethereum v1.9.14

### ISSUE THREAD

**Issue by hkalodner** [miguelmota/go-solidity-sha3#10]
The latest release of go-ethereum included a refactor which moved `abi.U256` from `"github.com/ethereum/go-ethereum/accounts/abi"` to `math.U256Bytes` in `github.com/ethereum/go-ethereum/common/math`. This will allow projects that make use of this package to bump to the latest go-ethereum version.

For context, here is the PR which made the breaking change: https://github.com/ethereum/go-ethereum/pull/21020.

**Comment by hkalodner** [comment]
I've opened a PR(https://github.com/miguelmota/go-solidity-sha3/pull/11) to fix this in case it's wanted/useful

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/go-solidity-sha3/pull/11
