### ISSUE TITLE
sha3 moved in go-ethereum repo

### ISSUE THREAD

**Issue by aleph2012** [miguelmota/go-solidity-sha3#4]
"github.com/ethereum/go-ethereum/crypto/sha3" ---> "golang.org/x/crypto/sha3"

https://github.com/ethereum/go-ethereum/commit/33d233d3e18359123993d3f54987441290faf212

go get on go-solidity-sha3 fails now because it can't find the sha3 dependency

**Comment by miguelmota** [comment]
@aleph2012 thanks for reporting. updated to the new package
