### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by michael-iglesias** [miguelmota/go-solidity-sha3#7]
I'm receiving the following error when trying to install. My GOPATH and everything that comes to mind is properly set-up. I even cloned the repo into `github.com/miguelmota/go-solidity-sha3` and ran `make deps` with no luck :(

Any ideas on how to resolve would be much appreciated!

```
$ go get -u github.com/miguelmota/go-solidity-sha3
# github.com/miguelmota/go-solidity-sha3/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
../github.com/miguelmota/go-solidity-sha3/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:42:10: fatal error: 'libsecp256k1/include/secp256
k1.h' file not found
#include "libsecp256k1/include/secp256k1.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by michael-iglesias** [comment]
Solved the issue by following the instructions listed in the following StackOverflow response...

https://stackoverflow.com/questions/51929021/header-file-not-found-when-running-go-vet-with-dep/51929022#51929022

**Comment by michael-iglesias** [comment]
Hmm... now I'm receiving the following error when trying to use the package. Still looks like a system issue, not sure how to remedy what is being thrown...?

```/usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1```

**Comment by miguelmota** [comment]
@michael-iglesias try completely removing the `vendor` directory and rerunning `GO111MODULE=on go mod vendor`
